// ./commands/animagine.js

const axios = require('axios');

const STYLE = {
    forwardingScore: 350,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363425394543602@newsletter',
        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
        serverMessageId: 202,
    },
};

module.exports = {
    name: 'animagine',
    aliases: ['animeimg', 'animeimage', 'generateanime'],
    category: 'ai',

    async execute({ sock, msg, args, jid }) {
        const prompt = args.join(' ');
        
        if (!prompt || prompt.trim().length < 3) {
            return sock.sendMessage(jid, {
                text: '🎨 *Animagine - AI Anime Generator*\n\n' +
                      '⚡ *Usage:* .animagine <description>\n\n' +
                      '✨ *Examples:*\n' +
                      '.animagine beautiful anime girl, cherry blossoms, sunset\n' +
                      '.animagine cyberpunk samurai, neon city, rain\n' +
                      '.animagine magical girl, stars, fantasy\n\n' +
                      '🎯 *Tips:*\n' +
                      '• Be specific about the scene\n' +
                      '• Add style keywords: 4k, detailed, anime\n' +
                      '• Include colors and mood',
                contextInfo: STYLE,
            }, { quoted: msg });
        }

        try {
            await sock.sendMessage(jid, { react: { text: '🎨', key: msg.key } });

            const url = `https://apis.davidcyriltech.my.id/animagine?prompt=${encodeURIComponent(prompt)}`;
            const response = await axios.get(url, { timeout: 60000 });
            const data = response.data;

            if (!data?.success || !data?.cdn_url) {
                throw new Error('Invalid response from API');
            }

            // Télécharger l'image
            const imgResponse = await axios.get(data.cdn_url, {
                responseType: 'arraybuffer',
                timeout: 30000,
            });
            const buffer = Buffer.from(imgResponse.data);

            await sock.sendMessage(jid, {
                image: buffer,
                caption: `🎨 *Animagine AI*\n\n` +
                         `📝 *Prompt:* ${prompt}\n` +
                         `📐 *Ratio:* ${data.ratio || '1:1'}\n\n` +
                         `⚡ _Generated by Zenitsu AI_`,
                contextInfo: STYLE,
            }, { quoted: msg });

            await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });

        } catch (err) {
            console.error('❌ Animagine error:', err.message);
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            return sock.sendMessage(jid, {
                text: '❌ *Failed to generate image*\n\n' +
                      `⚠️ Error: ${err.message}\n\n` +
                      '💡 Try again with a different prompt.',
                contextInfo: STYLE,
            }, { quoted: msg });
        }
    },
};
