// ./commands/animagine.js

const axios = require('axios');

const STYLE = {
    forwardingScore: 350,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363425394543602@newsletter',
        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
        serverMessageId: 202,
    },
};

module.exports = {
    name: 'animagine',
    aliases: ['animeimage', 'animeimg', 'generateanime'],
    category: 'ai',

    async execute({ sock, msg, args, jid }) {
        const prompt = args.join(' ');
        
        if (!prompt || prompt.trim().length < 3) {
            return sock.sendMessage(jid, {
                text: '🎨 *Animagine - AI Anime Generator*\n\n' +
                      '⚡ *Usage:* .animagine <description>\n\n' +
                      '✨ *Examples:*\n' +
                      '.animagine beautiful anime girl, cherry blossoms, sunset\n' +
                      '.animagine cyberpunk samurai, neon city, rain\n' +
                      '.animagine magical girl, stars, fantasy\n\n' +
                      '🎯 *Tips:*\n' +
                      '• Be specific about the scene\n' +
                      '• Add style keywords: 4k, detailed, anime\n' +
                      '• Include colors and mood',
                contextInfo: STYLE,
            }, { quoted: msg });
        }

        try {
            await sock.sendMessage(jid, { react: { text: '🎨', key: msg.key } });

            const url = `https://apis.davidcyriltech.my.id/animagine?prompt=${encodeURIComponent(prompt)}`;
            const response = await axios.get(url, {
                timeout: 60000,
                headers: { 'User-Agent': 'Mozilla/5.0' }
            });
            const data = response.data;

            if (!data?.success) {
                throw new Error('API response missing success flag');
            }

            let imageBuffer;

            // Cas 1 : l'API renvoie directement un champ image en base64
            if (data.image && typeof data.image === 'string' && data.image.startsWith('data:image')) {
                const base64 = data.image.split(',')[1];
                imageBuffer = Buffer.from(base64, 'base64');
            }
            // Cas 2 : l'API renvoie un CDN URL
            else if (data.cdn_url || data.url) {
                const imageUrl = data.cdn_url || data.url;
                const imgResponse = await axios.get(imageUrl, {
                    responseType: 'arraybuffer',
                    timeout: 30000,
                    headers: { 'User-Agent': 'Mozilla/5.0' }
                });
                imageBuffer = Buffer.from(imgResponse.data);
            } else {
                throw new Error('No image URL or base64 found in API response');
            }

            // Vérification de la taille minimale (évite les images vides)
            if (!imageBuffer || imageBuffer.length < 1024) {
                throw new Error('Downloaded image is too small or empty');
            }

            await sock.sendMessage(jid, {
                image: imageBuffer,
                caption: `🎨 *Animagine AI*\n\n` +
                         `📝 *Prompt:* ${prompt}\n` +
                         `📐 *Ratio:* ${data.ratio || '1:1'}\n\n` +
                         `⚡ _Generated by Zenitsu AI_`,
                contextInfo: STYLE,
            }, { quoted: msg });

            await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });

        } catch (err) {
            console.error('❌ Animagine error:', err.message);
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            return sock.sendMessage(jid, {
                text: '❌ *Failed to generate image*\n\n' +
                      `⚠️ Error: ${err.message}\n\n` +
                      '💡 Try again with a different prompt.',
                contextInfo: STYLE,
            }, { quoted: msg });
        }
    },
};
