// ./commands/flux.js

const axios = require('axios');

const STYLE = {
    forwardingScore: 350,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363425394543602@newsletter',
        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
        serverMessageId: 202,
    },
};

module.exports = {
    name: 'flux',
    aliases: ['fluxai', 'realistic', 'generate'],
    category: 'ai',

    async execute({ sock, msg, args, jid }) {
        const prompt = args.join(' ');
        
        if (!prompt || prompt.trim().length < 3) {
            return sock.sendMessage(jid, {
                text: '🖼️ *Flux AI - Realistic Image Generator*\n\n' +
                      '⚡ *Usage:* .flux <description>\n\n' +
                      '✨ *Examples:*\n' +
                      '.flux cyberpunk city, neon lights, rain\n' +
                      '.flux beautiful landscape, mountains, sunset\n' +
                      '.flux futuristic car, detailed, 8k\n\n' +
                      '🎯 *Tips:*\n' +
                      '• Be specific about the scene\n' +
                      '• Add style keywords: realistic, 4k, detailed\n' +
                      '• Include lighting and mood',
                contextInfo: STYLE,
            }, { quoted: msg });
        }

        try {
            await sock.sendMessage(jid, { react: { text: '🖼️', key: msg.key } });

            const url = `https://apis.davidcyriltech.my.id/fluxv2?prompt=${encodeURIComponent(prompt)}`;
            const response = await axios.get(url, { timeout: 60000 });
            const data = response.data;

            if (!data?.success || !data?.result) {
                throw new Error('Invalid response from API');
            }

            // Télécharger l'image
            const imgResponse = await axios.get(data.result, {
                responseType: 'arraybuffer',
                timeout: 30000,
            });
            const buffer = Buffer.from(imgResponse.data);

            await sock.sendMessage(jid, {
                image: buffer,
                caption: `🖼️ *Flux AI*\n\n` +
                         `📝 *Prompt:* ${prompt}\n\n` +
                         `⚡ _Generated by Zenitsu AI_`,
                contextInfo: STYLE,
            }, { quoted: msg });

            await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });

        } catch (err) {
            console.error('❌ Flux error:', err.message);
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            return sock.sendMessage(jid, {
                text: '❌ *Failed to generate image*\n\n' +
                      `⚠️ Error: ${err.message}\n\n` +
                      '💡 Try again with a different prompt.',
                contextInfo: STYLE,
            }, { quoted: msg });
        }
    },
};
