// ./commands/sora.js
const axios = require('axios');

module.exports = {
    name: 'sora',
    aliases: ['txt2img', 'text2img'],
    category: 'ai',

    async execute({ sock, msg, args, jid }) {
        const prompt = args.join(' ');

        if (!prompt || prompt.trim().length < 3) {
            return sock.sendMessage(jid, {
                text:
                    '🎨 *Sora AI Image Generator*\n\n' +
                    '⚡ *Usage:*\n' +
                    '.sora <prompt>\n\n' +
                    '✨ *Examples:*\n' +
                    '.sora A beautiful sunset over mountains\n' +
                    '.sora Cyberpunk city at night\n' +
                    '.sora Cute anime girl in garden',
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });
        }

        try { await sock.sendMessage(jid, { react: { text: '🎨', key: msg.key } }); } catch (_) {}

        try {
            const { data } = await axios.get(
                `https://apis.davidcyriltech.my.id/ai/dalle?text=${encodeURIComponent(prompt)}`,
                { timeout: 90000 }
            );

            let imageUrl = null;
            if (data?.result?.url) imageUrl = data.result.url;
            else if (data?.url) imageUrl = data.url;
            else if (data?.image_url) imageUrl = data.image_url;
            else if (typeof data === 'string' && data.startsWith('http')) imageUrl = data;

            if (!imageUrl) throw new Error('No image generated');

            await sock.sendMessage(jid, {
                image: { url: imageUrl },
                caption:
                    `🎨 *Sora AI*\n\n` +
                    `📝 *Prompt:* ${prompt}\n` +
                    `🔗 ${imageUrl}\n\n` +
                    `⚡ _Generated by Zenitsu_`,
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });

            try { await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } }); } catch (_) {}

        } catch (err) {
            console.error('❌ sora error:', err.message);
            try { await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } }); } catch (_) {}

            await sock.sendMessage(jid, {
                text: '❌ *Image Generation Failed*\n\nTry again with a different prompt.',
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });
        }
    },
};
